import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./new-globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { IconCopy } from "@tabler/icons-react";
import { IconPercentage60 } from "@tabler/icons-react";
import { IconForbidFilled } from "@tabler/icons-react";
import { IconFilter2 } from "@tabler/icons-react";
import { IconAdjustmentsHorizontal } from "@tabler/icons-react";
import "rsuite/dist/rsuite-no-reset.min.css";
import { Button } from "@/components/ui/button";
import { FilterDropdown } from "./filter-dropdown";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} global-styles layoutScrollbarObtrusive content-loaded loadingText is-bootstrapped loaded bootstrap-fade-complete`}
      >
        <SidebarProvider style={{ backgroundColor: "#fcfcfc" }}>
          <AppSidebar />
          <main className="w-full ">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
